name: (callable) Run Pytest
run-name: Run pytest

on:
  workflow_call:
    inputs:
      os:
        type: string
        required: true
      python-version:
        type: string
        required: true

jobs:
  run-pytest:
    runs-on: ${{ inputs.os }}
    steps:
      - name: uv install
        uses: astral-sh/setup-uv@v5
        with:
          # Install a specific version of uv.
          version: "0.5.14"

      - name: python
        run: uv python install ${{ inputs.python-version }}

      - name: checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: install pytest
        run: |
          uv sync --dev
          
      - name: run pytest
        run: make check-pytest
