name: On Push Tag to main
run-name: On Push tag to main

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*\.*\.*'

permissions:
  id-token: write  # IMPORTANT: mandatory for trusted publishing
  
jobs:
  build:
    uses: ./.github/workflows/callable-build-and-artifact.yml

  pypi:
    needs: build
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    uses: ./.github/workflows/callable-push-to-pypi.yml

  readthedocs:
    needs: build
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    uses: ./.github/workflows/callable-push-to-readthedocs.yml

